### ISSUE TITLE
Program down

### ISSUE THREAD

**Issue by fewensa** [msgport/ormpipe#41]
```
debug:   2024-02-04T05:29:52Z | [       ormpipe       ] [    ethers:sepolia     ] [receiveRpcResult] [{"jsonrpc":"2.0","result":"0x4f9698","id":29}]
error:   2024-02-04T05:29:52Z | [    ormpipe-relay    ] [arbitrumsepolia>sepolia] transaction execution reverted (action="sendTransaction", data=null, reason=null, invocation=null, revert=null, transaction={ "data": "", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "to": "0x0000000000808fE9bDCc1d180EfbF5C53552a6b1" }, receipt={ "_type": "TransactionReceipt", "blockHash": "0x87c4420fe62760799a122e4438f8f0786eb85e8804ec3c54a71cad4b2faf2be5", "blockNumber": 5215895, "contractAddress": null, "cumulativeGasUsed": "4846358", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "gasPrice": "3057312429", "gasUsed": "86169", "hash": "0xcb24cc598f27b19287958f4f746835ec29a52e1bccc133172ab9e0a2d2ff7da9", "index": 48, "logs": [  ], "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root": null, "status": 0, "to": "0x0000000000808fE9bDCc1d180EfbF5C53552a6b1" }, code=CALL_EXCEPTION, version=6.7.1)
Error: transaction execution reverted (action="sendTransaction", data=null, reason=null, invocation=null, revert=null, transaction={ "data": "", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "to": "0x0000000000808fE9bDCc1d180EfbF5C53552a6b1" }, receipt={ "_type": "TransactionReceipt", "blockHash": "0x87c4420fe62760799a122e4438f8f0786eb85e8804ec3c54a71cad4b2faf2be5", "blockNumber": 5215895, "contractAddress": null, "cumulativeGasUsed": "4846358", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "gasPrice": "3057312429", "gasUsed": "86169", "hash": "0xcb24cc598f27b19287958f4f746835ec29a52e1bccc133172ab9e0a2d2ff7da9", "index": 48, "logs": [  ], "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root": null, "status": 0, "to": "0x0000000000808fE9bDCc1d180EfbF5C53552a6b1" }, code=CALL_EXCEPTION, version=6.7.1)
    at makeError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at assert (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:142:15)
    at checkReceipt (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/provider.js:1047:35)
    at JsonRpcProvider.txListener (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/provider.js:1093:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
debug:   2024-02-04T05:29:52Z | [       ormpipe       ] [    ethers:sepolia     ] [receiveRpcError ] undefined
node:internal/errors:717
  const ex = new Error(msg);
             ^

Error: socket hang up
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketOnEnd (node:_http_client:526:23)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET'
}

Node.js v18.14.2
```

**Comment by fewensa** [comment]
![crab](https://github.com/msgport/ormpipe/assets/37804932/f4831b1e-7fcb-444f-8b4b-51b9932e16a6)

**Comment by fewensa** [comment]
Fixed
