### ISSUE TITLE
[BUG] Oracle import already used hash

### ISSUE THREAD

**Issue by jiguantong** [msgport/ormpipe#97]
```
info:    2024-06-23T11:56:19Z | [ormpipe-relay-oracle] [  darwinia>crab  ] [oracle:sign] new message accepted 0x0d73eff9c218fef378cfb7b039d704b08dbcb0c250bd0a08757e29188cf900ee wait block 2948828(darwinia) confirmed
info:    2024-06-23T11:56:19Z | [ormpipe-relay-oracle] [  darwinia>crab  ] [oracle:sign] message block confirmed 2973127/2948828(darwinia)
error:   2024-06-23T11:56:20Z | [   ormpipe-relay    ] [  darwinia>crab  ] execution reverted: "hash already used" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000116861736820616c72656164792075736564000000000000000000000000000000", reason="hash already used", transaction={ "data": "0x0589105b000000000000000000000000be01b76ab454ae2497ae43168b1f70c92ac1c72600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000066812ef800000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000840a863e6c000000000000000000000000000000000000000000000000000000000000002e00000000000000000000000013b2211a7ca45db2808f6db05557ce5347e3634e000000000000000000000000000000000000000000000000000000000000021d0d73eff9c218fef378cfb7b039d704b08dbcb0c250bd0a08757e29188cf900ee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c370e8f59449b4cae9b45c04a59161bde2a897295831ddef8006e18822c8928a322df3e633da88a4490c0d96c2ba786db8b8c2d3254a27ac708c3329d22b8b8e111ca4f45fe78948767bb403b927407b8265c15198bfc4db2fb91e818b7f1e73e19710c878a56a83afe9452e6c26ff00a8bd937ae85400d010f6774ffbaedffeec0d1b6e94655988610060e47a2c9a3a58a474a39f3b1a78e06af9871fec63d648a3342d1ccfd37d1e36610effba0d85f9bb23169de8cf7ece99915a57d68648142c9d1c0000000000000000000000000000000000000000000000000000000000", "from": "0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85", "to": "0x22117Db68370590c1031f52a6D1aDE3DCe0cCf9a" }, invocation=null, revert={ "args": [ "hash already used" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.7.1)
Error: execution reverted: "hash already used" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000116861736820616c72656164792075736564000000000000000000000000000000", reason="hash already used", transaction={ "data": "0x0589105b000000000000000000000000be01b76ab454ae2497ae43168b1f70c92ac1c72600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000066812ef800000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000840a863e6c000000000000000000000000000000000000000000000000000000000000002e00000000000000000000000013b2211a7ca45db2808f6db05557ce5347e3634e000000000000000000000000000000000000000000000000000000000000021d0d73eff9c218fef378cfb7b039d704b08dbcb0c250bd0a08757e29188cf900ee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c370e8f59449b4cae9b45c04a59161bde2a897295831ddef8006e18822c8928a322df3e633da88a4490c0d96c2ba786db8b8c2d3254a27ac708c3329d22b8b8e111ca4f45fe78948767bb403b927407b8265c15198bfc4db2fb91e818b7f1e73e19710c878a56a83afe9452e6c26ff00a8bd937ae85400d010f6774ffbaedffeec0d1b6e94655988610060e47a2c9a3a58a474a39f3b1a78e06af9871fec63d648a3342d1ccfd37d1e36610effba0d85f9bb23169de8cf7ece99915a57d68648142c9d1c0000000000000000000000000000000000000000000000000000000000", "from": "0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85", "to": "0x22117Db68370590c1031f52a6D1aDE3DCe0cCf9a" }, invocation=null, revert={ "args": [ "hash already used" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.7.1)
    at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at getBuiltinCallException (/app/node_modules/ethers/lib.commonjs/abi/abi-coder.js:104:37)
    at AbiCoder.getBuiltinCallException (/app/node_modules/ethers/lib.commonjs/abi/abi-coder.js:201:16)
    at JsonRpcProvider.getRpcError (/app/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:599:43)
    at /app/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:268:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jiguantong** [comment]
Crab ponder is stuck
